# Generated by Django 4.2.4 on 2023-08-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
